import Link from "next/link";
import { ArrowRight, BookOpen, Bot, Gamepad2, Radio, Sparkles, Trophy, UserRound } from "lucide-react";

import AppLayout from "@/app/components/AppLayout";

const sections = [
  { href: "/game-night", eyebrow: "La experiencia principal", title: "Game Night", description: "Crea tu Mesa, organiza personas o equipos, controla el tiempo y lleva el marcador de toda la noche.", icon: Gamepad2, art: "🎉", accent: "from-emerald-500 via-emerald-700 to-[#063d32]", badge: "ANFITRIÓN" },
  { href: "/online", eyebrow: "Con amigos a distancia", title: "Juegos Online", description: "Crea una sala privada, comparte un código y juega con tus amigos desde cualquier lugar.", icon: Radio, art: "🌐", accent: "from-blue-500 via-blue-700 to-[#071d50]", badge: "ONLINE" },
  { href: "/tournaments", eyebrow: "Desafío individual", title: "Torneos", description: "Reta a la IA en Trivia, supera tus marcas y gana monedas y XP para tu perfil.", icon: Trophy, art: "🏆", accent: "from-violet-500 via-indigo-700 to-[#24124d]", badge: "RECOMPENSAS" },
  { href: "/solo", eyebrow: "A tu ritmo", title: "Jugar Solo", description: "Disfruta partidas individuales, practica y descubre desafíos sin necesitar una sala.", icon: Bot, art: "🧠", accent: "from-fuchsia-500 via-purple-700 to-[#2a103d]", badge: "SOLO" },
  { href: "/games", eyebrow: "Todo en un lugar", title: "Biblioteca", description: "Explora todos los juegos, sus reglas, contenido localizado y el estado de cada Beta Test.", icon: BookOpen, art: "🎲", accent: "from-amber-500 via-orange-700 to-[#4a1d08]", badge: "JUEGOS" },
] as const;

export default function DashboardPage() {
  return <AppLayout><main className="mx-auto max-w-6xl space-y-6 pb-4 md:space-y-8">
    <section className="relative overflow-hidden rounded-[2rem] border border-blue-200/20 bg-[linear-gradient(130deg,#06142e,#123574_58%,#08152e)] p-6 shadow-2xl shadow-blue-950/40 md:p-10"><div className="absolute -right-10 -top-12 h-44 w-44 rounded-full bg-blue-400/20 blur-3xl" /><div className="absolute -bottom-16 left-1/3 h-32 w-32 rounded-full bg-violet-500/20 blur-3xl" /><div className="relative max-w-3xl"><p className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.28em] text-amber-300"><Sparkles size={14} /> La Mesa · Game Night</p><h1 className="mt-3 text-4xl font-black leading-[1.04] sm:text-5xl md:text-6xl">Tu noche. Tus juegos. Tu Mesa.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-blue-100/80 md:text-lg">La Mesa es tu anfitrión digital: reúne a todos, explica el juego, maneja turnos y convierte cualquier reunión en una gran noche.</p></div></section>
    <section><div className="mb-4"><p className="text-[10px] font-black uppercase tracking-[.25em] text-blue-300">Empieza aquí</p><h2 className="mt-1 text-2xl font-black md:text-3xl">Elige tu experiencia</h2></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{sections.map((section) => { const Icon = section.icon; return <Link key={section.href} href={section.href} className={`group relative min-h-64 overflow-hidden rounded-3xl border border-white/20 bg-gradient-to-br p-5 shadow-xl shadow-black/25 transition duration-300 hover:-translate-y-1 hover:border-white/55 md:p-6 ${section.accent}`}><span className="absolute -right-5 -top-9 text-[9rem] opacity-15 transition duration-300 group-hover:scale-110">{section.art}</span><div className="relative flex items-start justify-between gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl border border-white/25 bg-black/15"><Icon size={24} /></span><span className="rounded-full bg-white/15 px-2.5 py-1 text-[10px] font-black tracking-wide">{section.badge}</span></div><div className="relative mt-8"><p className="text-[10px] font-black uppercase tracking-[.2em] text-white/65">{section.eyebrow}</p><h3 className="mt-2 text-3xl font-black">{section.title}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-white/80">{section.description}</p><span className="mt-5 flex items-center gap-1 text-sm font-black">Entrar <ArrowRight size={17} /></span></div></Link>; })}</div></section>
    <section className="mesa-panel flex flex-col gap-4 rounded-2xl p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-500/15 text-blue-300"><UserRound size={22} /></span><div><p className="font-black">Tu progreso está guardado en tu perfil</p><p className="mt-1 text-sm text-slate-400">Monedas, XP, nivel y recompensas viven fuera de esta portada.</p></div></div><Link href="/profile" className="inline-flex shrink-0 items-center gap-2 rounded-xl border border-slate-600 px-4 py-2.5 text-sm font-black hover:bg-slate-800">Ver perfil <ArrowRight size={16} /></Link></section>
  </main></AppLayout>;
}
